const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const elements = new Map();
const element = id => { if (!elements.has(id)) elements.set(id,{value:'',innerHTML:'',classList:{add(){},remove(){}},addEventListener(){},click(){},setAttribute(){}}); return elements.get(id); };
let stored;
const ctx = vm.createContext({console,Date,Math,Set,Map,JSON,Number,String,Object,Array,confirm:()=>true,setTimeout:()=>{},localStorage:{getItem:()=>stored,setItem:(k,v)=>{stored=v},removeItem:()=>{stored=null}},document:{readyState:'loading',addEventListener(){},getElementById:element,querySelector:()=>element('nav'),querySelectorAll:()=>[]}});
vm.runInContext(fs.readFileSync('app.js','utf8'),ctx);
const run = code => vm.runInContext(code,ctx);
run(`renderApp = () => {}; showToast = () => {}; openLeaderboard = () => {};
function fixture(count=8) {
 const d=getDefaultData();
 d.players=Array.from({length:count},(_,i)=>({id:'p'+i,name:i<2?'Same name':'Player '+i,isActive:true,gamesPlayed:0,lastPlayedGameNumber:null,waitingSinceGameNumber:0,partnerHistory:[],opponentHistory:[]}));
 d.activeSession={sessionId:'s',sessionName:'Test',sessionNumber:1,status:'active',queueMode:'fair_rotation',dateStarted:new Date().toISOString(),games:[],currentGame:null,playerStats:{}};
 return d;
}
let d=fixture(); saveData(d);`);
assert.equal(run('generateNextGame()'),true);
assert.equal(run('loadData().activeSession.currentGame.status'),'in_progress');
assert.equal(run('generateNextGame()'),false,'single court guard');
assert.equal(run('loadData().players.reduce((n,p)=>n+p.gamesPlayed,0)'),0,'preview/start do not increment stats');
assert.equal(run(`(()=>{const d=loadData();return d.activeSession.pendingGame.teamA.concat(d.activeSession.pendingGame.teamB).every(p=>!getCurrentPlayingIds(d).includes(p.id))})()`),true,'eight-player preview rotates to waiting players');
const pending = run('loadData().activeSession.pendingGame.gameId');
element('teamAScoreInput').value='11'; element('teamBScoreInput').value='5';
assert.equal(run('completeCurrentGame()'),true);
assert.equal(run('completeCurrentGame()'),false,'duplicate completion guard');
assert.equal(run('loadData().activeSession.games.length'),1);
assert.equal(run('getLeaderboard(loadData().activeSession).length'),4);
assert.equal(run('getLeaderboard(loadData().activeSession).filter(p=>p.wins===1).length'),2);
assert.equal(run('loadData().players.reduce((n,p)=>n+p.gamesPlayed,0)'),4);
assert.equal(run('loadData().activeSession.pendingGame.gameId'),pending,'preserve pending after completion and reload');
assert.equal(run('generateNextGame()'),true);
assert.equal(run('loadData().activeSession.currentGame.gameId'),pending,'start saved assignment');
assert.equal(run('endSession()'),false,'cannot end active match');
assert.equal(run('cancelCurrentGame()'),true);
assert.equal(run('loadData().activeSession.cancelledGames[0].status'),'cancelled');
assert.equal(run('endSession()'),true);
assert.equal(run('loadData().players.length'),8,'end preserves players');
assert.equal(run('loadData().pastSessions[0].finalLeaderboard.length'),4);
run(`d=fixture(4); saveData(d); generateNextGame();`);
assert.equal(run('loadData().activeSession.pendingGame.teamA.concat(loadData().activeSession.pendingGame.teamB).length'),4,'four player reuse');
run(`d=loadData(); d.players[0].isActive=false; ensurePendingGame(d); saveData(d);`);
assert.equal(run('loadData().activeSession.pendingGame'),null,'invalidate inactive lineup');
run(`d=fixture(3); saveData(d);`);
assert.equal(run('generateNextGame()'),false);
assert.equal(run('validatePickleballScore(11,11).isValid'),false);
assert.equal(run('validatePickleballScore(11,10).isValid'),false);
assert.equal(run('validatePickleballScore(12,10).isValid'),true);
assert.equal(run(`getLeaderboard({games:[{status:'completed',teamA:[{id:'a',name:'a'},{id:'b',name:'b'}],teamB:[{id:'c',name:'c'},{id:'e',name:'e'}],winningTeam:'A',teamAScore:null,teamBScore:null}]}).length`),0,'legacy winners without scores excluded');
assert.equal(run(`migrateData({players:[],settings:{currentGameNumber:1},currentGame:{teamA:[],teamB:[],status:'current'},pastGames:[]}).activeSession.currentGame.status`),'in_progress');
run(`d=fixture(); ensurePendingGame(d); const imported=migrateData(JSON.parse(JSON.stringify(d))); saveData(imported);`);
assert.equal(run('isPendingValid(loadData())'),true,'backup roundtrip');
console.log('PASS: rotation, preview isolation, saved lineup promotion, duplicate guards, cancellation, final snapshot, player preservation, four-player reuse, unavailable lineup, scoring, legacy migration, backup roundtrip');
run(`d=fixture(); saveData(d); generateNextGame(); renderUpcoming(loadData()); renderLeaderboard(loadData());`);
assert.ok(!element('leaderboardSection').innerHTML.includes('class="podium"'),'podium hidden while active');
assert.ok(element('upcomingGameSection').innerHTML.includes('disabled'),'start disabled during current game');
element('teamAScoreInput').value='11'; element('teamBScoreInput').value='4';
run('completeCurrentGame(); renderUpcoming(loadData());');
assert.ok(!element('upcomingGameSection').innerHTML.includes('disabled'),'completion enables next start');
run('endSession(); leaderboardSessionId = loadData().pastSessions[0].sessionId; renderLeaderboard(loadData());');
assert.ok(element('leaderboardSection').innerHTML.includes('class="podium"'),'final podium revealed');
assert.ok(element('leaderboardSection').innerHTML.includes('place-1'));
run(`leaderboardSessionId=null; d=fixture(); saveData(d); endSession();`);
assert.equal(run('loadData().pastSessions[0].finalLeaderboard.length'),0,'empty session ends safely');
run(`d=fixture(8); d.activeSession.queueMode='winner_priority'; saveData(d); generateNextGame();`);
assert.equal(run('isPendingValid(loadData())'),true,'winner priority pending');
assert.equal(run('loadData().players.reduce((n,p)=>n+p.gamesPlayed,0)'),0);
run(`d=loadData(); const unavailable=d.activeSession.pendingGame.teamA[0].id; d.players.find(p=>p.id===unavailable).isAvailable=false; ensurePendingGame(d); saveData(d);`);
assert.equal(run('isPendingValid(loadData())'),true,'regenerate unavailable player');
console.log('PASS: active/final podium rendering, disabled start, empty session, winner priority and unavailable player regeneration');
run(`
const scoredMatch=(teamA,teamB,a,b)=>({status:'completed',teamA:teamA.map(id=>({id,name:id})),teamB:teamB.map(id=>({id,name:id})),teamAScore:a,teamBScore:b});
const pointsSession={status:'completed',games:[scoredMatch(['a','b'],['c','d'],11,0),scoredMatch(['c','d'],['e','f'],20,22)]};
`);
assert.equal(run('getLeaderboard(pointsSession)[0].playerId'),'e');
assert.equal(run('getLeaderboard(pointsSession).find(p=>p.playerId==="c").pointsFor'),20);
assert.equal(run('getLeaderboard(pointsSession).find(p=>p.playerId==="c").pointsAgainst'),33);
assert.ok(run('getLeaderboard(pointsSession).find(p=>p.playerId==="c").rank < getLeaderboard(pointsSession).find(p=>p.playerId==="a").rank'),'more points outrank more wins');
run(`const migratedPoints=migrateSession({...pointsSession,finalLeaderboard:[{playerId:'a',rank:1}]});`);
assert.equal(run('migratedPoints.finalLeaderboard[0].playerId'),'e','old final snapshot reranked');
assert.equal(run('migratedPoints.leaderboardRanking'),'points');
assert.equal(run(`getLeaderboard({games:[scoredMatch(['a','b'],['c','d'],11,4),scoredMatch(['c','d'],['e','f'],2,11)]})[0].playerId`),'e','points tie uses point difference');
console.log('PASS: points accumulation, points ahead of wins, point-difference ties, past snapshot migration');
for (const mode of ['fair_rotation', 'winner_priority']) {
    run(`d=fixture(4); d.activeSession.queueMode='${mode}'; saveData(d);`);
    for (let i=0; i<12; i++) {
        assert.equal(run('generateNextGame()'),true);
        assert.equal(run(`(()=>{const d=loadData(); const s={...d.activeSession,currentGame:null}; return [d.activeSession.currentGame.teamA,d.activeSession.currentGame.teamB].every(t=>!repeatsLastPartner(d.players.find(p=>p.id===t[0].id),d.players.find(p=>p.id===t[1].id),s));})()`),true,mode+' never repeats each player last partner');
        assert.equal(run('isPendingValid(loadData())'),true,'preview accounts for ongoing match');
        element('teamAScoreInput').value='11'; element('teamBScoreInput').value='3';
        assert.equal(run('completeCurrentGame()'),true);
    }
}
run(`d=fixture(4); d.players[0].partnerHistory=['p1']; d.players[1].partnerHistory=['p0']; d.players[2].partnerHistory=['p3']; d.players[3].partnerHistory=['p2']; saveData(d); generateNextGame();`);
assert.equal(run(`(()=>{const d=loadData(); return [d.activeSession.currentGame.teamA,d.activeSession.currentGame.teamB].every(t=>!repeatsLastPartner(d.players.find(p=>p.id===t[0].id),d.players.find(p=>p.id===t[1].id),null));})()`),true,'previous session partner history honored');
run(`d=fixture(4); d.players[1].partnerHistory=['p0']; d.players[2].partnerHistory=['p0']; d.players[3].partnerHistory=['p0']; saveData(d);`);
assert.equal(run('generateNextGame()'),false,'impossible partner constraint blocks game');
assert.equal(run('loadData().activeSession.currentGame'),null);
run(`d=fixture(4); d.players[0].partnerHistory=['p1']; d.players[1].partnerHistory=['p0']; d.activeSession.pendingGame={gameId:'old',status:'pending',teamA:[d.players[0],d.players[1]],teamB:[d.players[2],d.players[3]]};`);
assert.equal(run('isPendingValid(d)'),false,'old repeating preview invalidated');
console.log('PASS: both modes change partners across 12 matches, ongoing-match previews, cross-session history, impossible pairing guard, legacy preview invalidation');
ctx.ScoringEngine = require('./scoring-engine.js');
run(`d=fixture(4); saveData(d); generateNextGame(); d=loadData(); let match=d.activeSession.currentGame; let scoring=ScoringEngine.create(match,{firstServingTeam:'A',startingRight:{A:match.teamA[1].id,B:match.teamB[1].id},target:15}); scoring=ScoringEngine.correct(scoring,{scores:{A:14,B:13},positions:ScoringEngine.positionsFor(scoring.teams,scoring.initialConfig.startingRight,{A:14,B:13}),servingTeam:'A',serverId:match.teamA[1].id,serverNumber:1}); match.scoringState=scoring; saveData(d);`);
assert.equal(run('completeCurrentGame()'),false,'configured 15-point game cannot finish at 14');
run(`d=loadData(); match=d.activeSession.currentGame; match.scoringState=ScoringEngine.rally(match.scoringState,'A'); saveData(d);`);
assert.equal(run(`completeCurrentGame({expectedGameId:'stale'})`),false,'stale scoring page cannot finalize');
assert.equal(run(`completeCurrentGame({expectedRevision:-1})`),false,'stale revision cannot finalize');
assert.equal(run('completeCurrentGame()'),true,'save engine game via common completion');
assert.equal(run('completeCurrentGame()'),false,'no duplicate finalized records');
assert.equal(run('loadData().activeSession.games[0].teamAScore'),15);
assert.equal(run('loadData().activeSession.games[0].targetScore'),15);
assert.equal(run('getLeaderboard(loadData().activeSession)[0].pointsFor'),15);
assert.equal(run('loadData().players.reduce((n,p)=>n+p.gamesPlayed,0)'),4);
assert.equal(run('loadData().activeSession.games[0].scoringState.history.length'),2,'rally and correction audit retained');
console.log('PASS: shared scoring completion, 15-point target, stale match/revision guards, statistics and history preservation');
